#
# This docker-compose file starts and runs:
# * A 3-node kafka cluster
# * A 1-zookeeper ensemble
# * Schema Registry
# * Kafka REST Proxy
# * Kafka Connect
#

version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.2
    network_mode: host
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"

  kafka0:
    image: confluentinc/cp-kafka:5.2.2
    network_mode: host
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://localhost:19092,EXTERNAL://localhost:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    depends_on:
      - "zookeeper"

  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.2.2
    network_mode: host
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://localhost:9092"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082/"
      KAFKA_REST_HOST_NAME: "rest-proxy"
    depends_on:
      - "kafka0"

  topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    network_mode: host
    ports:
      - "8085:8085"
    environment:
      PORT: "8085"
      PROXY: "true"
      KAFKA_REST_PROXY_URL: "http://localhost:8082"
    depends_on:
      - "rest-proxy"

  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    network_mode: host
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./radio_code.json:/dados/projetos/streams/sf-crime-data-project-nanodegree/radio_code.json
      - ./master.sh:/master.sh
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_HOST=localhost
      - SPARK_LOCAL_IP=127.0.0.1
      - "constraint:node==master1"

  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-1
    network_mode: host
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./radio_code.json:/dados/projetos/streams/sf-crime-data-project-nanodegree/radio_code.json
    environment:
      - "SPARK_MASTER=spark://localhost:7077"
      - "constraint:node==worker1"
